package com.sda.jz75_security_template.model;

public enum TypWyroznienia {
    KONKURS_MATEMATYCZNY,
    KONKURS_HISTORYCZNY,
    KONKURS_PRZYRODNICZY,
    KONKURS_INFORMATYCZNY,
    KONKURS_ORTOGRAFICZNY,
    KONKURS_GEOGRAFICZNY,
    KONKURS_ANGIELSKIEGO,
    ZAWODY_SPORTOWE,
    WOLONTARIAT

}
